# Generated by Django 5.2.12 on 2026-03-24 19:00

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('resume_file', models.FileField(blank=True, null=True, upload_to='resumes/')),
                ('job_description', models.TextField(blank=True, null=True)),
                ('resume_score', models.IntegerField(blank=True, null=True)),
                ('resume_strengths', models.JSONField(blank=True, default=list)),
                ('resume_red_flags', models.JSONField(blank=True, default=list)),
                ('resume_recommendation', models.CharField(blank=True, choices=[('interview', 'Interview'), ('reject', 'Reject'), ('maybe', 'Maybe')], max_length=20, null=True)),
                ('resume_analysis', models.JSONField(blank=True, null=True)),
                ('interview_status', models.CharField(choices=[('pending', 'Pending'), ('scheduled', 'Scheduled'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('vapi_call_id', models.CharField(blank=True, max_length=255, null=True)),
                ('interview_transcript', models.TextField(blank=True, null=True)),
                ('interview_score', models.IntegerField(blank=True, null=True)),
                ('interview_analysis', models.JSONField(blank=True, null=True)),
                ('scheduled_interview_time', models.DateTimeField(blank=True, null=True)),
                ('interview_reminder_sent', models.BooleanField(default=False)),
                ('overall_score', models.IntegerField(blank=True, null=True)),
                ('final_status', models.CharField(choices=[('new', 'New'), ('screening', 'Screening'), ('interviewing', 'Interviewing'), ('shortlisted', 'Shortlisted'), ('rejected', 'Rejected')], default='new', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-overall_score', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InterviewSlot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('is_booked', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('candidate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='booked_slot', to='hiring.candidate')),
            ],
            options={
                'ordering': ['start_time'],
            },
        ),
    ]
